-- Seed: 5 blog posts.
-- Idempotent: re-running upserts on slug.

insert into public.blog_posts
    (slug, title, excerpt, category, author, published_at, reading_time, cover_image, sections)
values
    ('the-hidden-cost-of-software-that-almost-fits', 'The Hidden Cost of Software That Almost Fits', 'Off-the-shelf tools that nearly match your workflow quietly tax every team that touches them. Here is how to spot the drag — and when to build instead.', 'Software Engineering', 'ScaleJade Engineering', '2026-06-18'::date, '4 min read', null, '[{"paragraphs":["Off-the-shelf tools that nearly match your workflow quietly tax every team that touches them. Here is how to spot the drag — and when to build instead. It is a pattern we see across organizations of every size, and it rarely announces itself loudly.","We approach software engineering the way good engineering always works: understand the problem, build for the real environment, and stay until the result is genuinely yours."]},{"heading":"What we have learned","paragraphs":["The teams that succeed treat the unglamorous parts as first-class work — the foundations, the testing, the operational discipline that keeps a system honest long after launch.","Advantage comes from the whole system, not a single clever decision. Each layer has to earn the trust of the layer above it."],"image":"https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1600&q=80","imageCaption":"Engineering teams working as long-term partners, not contractors."},{"heading":"Where to start","paragraphs":["Before any code, the most valuable question is where this work creates genuine, measurable value — and where it does not justify the investment.","If this is on your roadmap and you want it done properly, the path is the same one we take with every client: deliberate, accountable, and built to last."]}]'::jsonb),
    ('legacy-systems-carry-institutional-knowledge', 'Legacy Systems Carry Institutional Knowledge', 'Modernizing an aging system is rarely about the code. It is about preserving the decades of decisions encoded inside it.', 'Software Engineering', 'ScaleJade Engineering', '2026-06-09'::date, '5 min read', null, '[{"paragraphs":["Modernizing an aging system is rarely about the code. It is about preserving the decades of decisions encoded inside it. It is a pattern we see across organizations of every size, and it rarely announces itself loudly.","We approach software engineering the way good engineering always works: understand the problem, build for the real environment, and stay until the result is genuinely yours."]},{"heading":"What we have learned","paragraphs":["The teams that succeed treat the unglamorous parts as first-class work — the foundations, the testing, the operational discipline that keeps a system honest long after launch.","Advantage comes from the whole system, not a single clever decision. Each layer has to earn the trust of the layer above it."],"image":"https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1600&q=80","imageCaption":"Modernizing without discarding the knowledge an old system encodes."},{"heading":"Where to start","paragraphs":["Before any code, the most valuable question is where this work creates genuine, measurable value — and where it does not justify the investment.","If this is on your roadmap and you want it done properly, the path is the same one we take with every client: deliberate, accountable, and built to last."]}]'::jsonb),
    ('why-we-embed-engineers-instead-of-handing-off', 'Why We Embed Engineers Instead of Handing Off', 'Contractors deliver and disappear. We stay until the system is stable, understood, and genuinely yours.', 'Software Engineering', 'ScaleJade Engineering', '2026-05-31'::date, '6 min read', null, '[{"paragraphs":["Contractors deliver and disappear. We stay until the system is stable, understood, and genuinely yours. It is a pattern we see across organizations of every size, and it rarely announces itself loudly.","We approach software engineering the way good engineering always works: understand the problem, build for the real environment, and stay until the result is genuinely yours."]},{"heading":"What we have learned","paragraphs":["The teams that succeed treat the unglamorous parts as first-class work — the foundations, the testing, the operational discipline that keeps a system honest long after launch.","Advantage comes from the whole system, not a single clever decision. Each layer has to earn the trust of the layer above it."],"image":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1600&q=80","imageCaption":"Senior engineers embedded as an extension of your own team."},{"heading":"Where to start","paragraphs":["Before any code, the most valuable question is where this work creates genuine, measurable value — and where it does not justify the investment.","If this is on your roadmap and you want it done properly, the path is the same one we take with every client: deliberate, accountable, and built to last."]}]'::jsonb),
    ('test-automation-is-risk-management-not-overhead', 'Test Automation Is Risk Management, Not Overhead', 'Reliability at scale needs more than code review. Automated quality gates catch regressions before your users do.', 'Software Engineering', 'ScaleJade Engineering', '2026-05-22'::date, '7 min read', null, '[{"paragraphs":["Reliability at scale needs more than code review. Automated quality gates catch regressions before your users do. It is a pattern we see across organizations of every size, and it rarely announces itself loudly.","We approach software engineering the way good engineering always works: understand the problem, build for the real environment, and stay until the result is genuinely yours."]},{"heading":"What we have learned","paragraphs":["The teams that succeed treat the unglamorous parts as first-class work — the foundations, the testing, the operational discipline that keeps a system honest long after launch.","Advantage comes from the whole system, not a single clever decision. Each layer has to earn the trust of the layer above it."],"image":"https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1600&q=80","imageCaption":"Automated quality gates that catch regressions before production."},{"heading":"Where to start","paragraphs":["Before any code, the most valuable question is where this work creates genuine, measurable value — and where it does not justify the investment.","If this is on your roadmap and you want it done properly, the path is the same one we take with every client: deliberate, accountable, and built to last."]}]'::jsonb),
    ('designing-apis-your-future-self-won-t-resent', 'Designing APIs Your Future Self Won''t Resent', 'The seams between systems are where complexity hides. Clean integration is a design discipline, not an afterthought.', 'Software Engineering', 'ScaleJade Engineering', '2026-05-13'::date, '8 min read', null, '[{"paragraphs":["The seams between systems are where complexity hides. Clean integration is a design discipline, not an afterthought. It is a pattern we see across organizations of every size, and it rarely announces itself loudly.","We approach software engineering the way good engineering always works: understand the problem, build for the real environment, and stay until the result is genuinely yours."]},{"heading":"What we have learned","paragraphs":["The teams that succeed treat the unglamorous parts as first-class work — the foundations, the testing, the operational discipline that keeps a system honest long after launch.","Advantage comes from the whole system, not a single clever decision. Each layer has to earn the trust of the layer above it."],"image":"https://images.unsplash.com/photo-1607799279861-4dd421887fb3?auto=format&fit=crop&w=1600&q=80","imageCaption":"Clean integration so the seams between systems disappear."},{"heading":"Where to start","paragraphs":["Before any code, the most valuable question is where this work creates genuine, measurable value — and where it does not justify the investment.","If this is on your roadmap and you want it done properly, the path is the same one we take with every client: deliberate, accountable, and built to last."]}]'::jsonb)
on conflict (slug) do update set
    title = excluded.title,
    excerpt = excluded.excerpt,
    category = excluded.category,
    author = excluded.author,
    published_at = excluded.published_at,
    reading_time = excluded.reading_time,
    cover_image = excluded.cover_image,
    sections = excluded.sections;
